# List of 100 popular and influential books
POPULAR_BOOKS = [
    "To Kill a Mockingbird",
    "1984",
    "The Great Gatsby",
    "Pride and Prejudice",
    "The Catcher in the Rye",
    "The Hobbit",
    "Harry Potter and the Sorcerer's Stone",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Diary of a Young Girl",
    "Moby-Dick",
    "The Hunger Games",
    "The Fault in Our Stars",
    "A Game of Thrones",
    "Brave New World",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "The Alchemist",
    "The Picture of Dorian Gray",
    "Crime and Punishment",
    "The Book Thief",
    "The Kite Runner",
    "Jane Eyre",
    "Wuthering Heights",
    "Catch-22",
    "The Shining",
    "The Outsiders",
    "The Odyssey",
    "Fahrenheit 451",
    "The Handmaid's Tale"
]
